import { Balance } from "../types/balance";

const mock = () => +(Math.random() * 1000).toFixed(4);

export const MOCK_BALANCE : Array<Balance> = [
  { currency: "BLUR", balance: mock() },
  { currency: "bNEO", balance: mock() },
  { currency: "BUSD", balance: mock() },
  { currency: "BUSD", balance: mock() },
  { currency: "USD", balance: mock() },
  { currency: "ETH", balance: mock() },
  { currency: "GMX", balance: mock() },
  { currency: "STEVMOS", balance: mock() },
  { currency: "LUNA", balance: mock() },
  { currency: "RATOM", balance: mock() },
  { currency: "STRD", balance: mock() },
  { currency: "EVMOS", balance: mock() },
  { currency: "IBCX", balance: mock() },
  { currency: "IRIS", balance: mock() },
  { currency: "ampLUNA", balance: mock() },
  { currency: "KUJI", balance: mock() },
  { currency: "STOSMO", balance: mock() },
  { currency: "USDC", balance: mock() },
  { currency: "axlUSDC", balance: mock() },
  { currency: "ATOM", balance: mock() },
  { currency: "STATOM", balance: mock() },
  { currency: "OSMO", balance: mock() },
  { currency: "rSWTH", balance: mock() },
  { currency: "STLUNA", balance: mock() },
  { currency: "LSI", balance: mock() },
  { currency: "OKB", balance: mock() },
  { currency: "OKT", balance: mock() },
  { currency: "SWTH", balance: mock() },
  { currency: "USC", balance: mock() },
  { currency: "USDC", balance: mock() },
  { currency: "USDC", balance: mock() },
  { currency: "USDC", balance: mock() },
  { currency: "WBTC", balance: mock() },
  { currency: "wstETH", balance: mock() },
  { currency: "YieldUSD", balance: mock() },
  { currency: "ZIL", balance: mock() },
];
