
export function useErrorMess(a: any, t: any) {
    // const { t } = useTranslation();
    switch (a) {
        case "1": { return t("common.mess.TTSwapError.1"); }
        case "2": { return t("common.mess.TTSwapError.2"); }
        case "3": { return t("common.mess.TTSwapError.3"); }
        case "4": { return t("common.mess.TTSwapError.4"); }
        case "5": { return t("common.mess.TTSwapError.5"); }
        case "6": { return t("common.mess.TTSwapError.6"); }
        case "7": { return t("common.mess.TTSwapError.7"); }
        case "8": { return t("common.mess.TTSwapError.8"); }
        case "9": { return t("common.mess.TTSwapError.9"); }
        case "10": { return t("common.mess.TTSwapError.10"); }
        case "11": { return t("common.mess.TTSwapError.11"); }
        case "12": { return t("common.mess.TTSwapError.12"); }
        case "13": { return t("common.mess.TTSwapError.13"); }
        case "14": { return t("common.mess.TTSwapError.14"); }
        case "15": { return t("common.mess.TTSwapError.15"); }
        case "16": { return t("common.mess.TTSwapError.16"); }
        case "17": { return t("common.mess.TTSwapError.17"); }
        case "18": { return t("common.mess.TTSwapError.18"); }
        case "19": { return t("common.mess.TTSwapError.19"); }
        case "20": { return t("common.mess.TTSwapError.20"); }
        case "21": { return t("common.mess.TTSwapError.21"); }
        case "22": { return t("common.mess.TTSwapError.22"); }
        case "23": { return t("common.mess.TTSwapError.23"); }
        case "24": { return t("common.mess.TTSwapError.24"); }
        case "25": { return t("common.mess.TTSwapError.25"); }
        case "26": { return t("common.mess.TTSwapError.26"); }
        case "27": { return t("common.mess.TTSwapError.27"); }
        case "28": { return t("common.mess.TTSwapError.28"); }
        case "29": { return t("common.mess.TTSwapError.29"); }
        case "30": { return t("common.mess.TTSwapError.30"); }
        case "31": { return t("common.mess.TTSwapError.31"); }
        case "32": { return t("common.mess.TTSwapError.32"); }
        case "33": { return t("common.mess.TTSwapError.33"); }
        case "34": { return t("common.mess.TTSwapError.34"); }
        case "35": { return t("common.mess.TTSwapError.35"); }
        case "36": { return t("common.mess.TTSwapError.36"); }
        case "37": { return t("common.mess.TTSwapError.37"); }
        case "38": { return t("common.mess.TTSwapError.38"); }
        case "39": { return t("common.mess.TTSwapError.39"); }
        case "40": { return t("common.mess.TTSwapError.40"); }
        case "41": { return t("common.mess.TTSwapError.41"); }
        case "42": { return t("common.mess.TTSwapError.42"); }
        case "43": { return t("common.mess.TTSwapError.43"); }
        case "44": { return t("common.mess.TTSwapError.44"); }
        case "45": { return t("common.mess.TTSwapError.45"); }
        case "46": { return t("common.mess.TTSwapError.46"); }
        case "47": { return t("common.mess.TTSwapError.47"); }
        case "48": { return t("common.mess.TTSwapError.48"); }
        case "49": { return t("common.mess.TTSwapError.49"); }
        case "50": { return t("common.mess.TTSwapError.50"); }
        case "51": { return t("common.mess.TTSwapError.51"); }
        case "52": { return t("common.mess.TTSwapError.52"); }
        case "53": { return t("common.mess.TTSwapError.53"); }
        case "54": { return t("common.mess.TTSwapError.54"); }
        case "55": { return t("common.mess.TTSwapError.55"); }
        case "56": { return t("common.mess.TTSwapError.56"); }
        case "57": { return t("common.mess.TTSwapError.57"); }
        case "58": { return t("common.mess.TTSwapError.58"); }
        case "59": { return t("common.mess.TTSwapError.59"); }
        case "60": { return t("common.mess.TTSwapError.60"); }
        case "61": { return t("common.mess.TTSwapError.61"); }
        case "62": { return t("common.mess.TTSwapError.62"); }
        case "63": { return t("common.mess.TTSwapError.63"); }
        case "64": { return t("common.mess.TTSwapError.64"); }
        case "65": { return t("common.mess.TTSwapError.65"); }
        case "66": { return t("common.mess.TTSwapError.66"); }
        case "67": { return t("common.mess.TTSwapError.67"); }
        case "68": { return t("common.mess.TTSwapError.68"); }
        case "69": { return t("common.mess.TTSwapError.69"); }
        case "70": { return t("common.mess.TTSwapError.70"); }
        case "71": { return t("common.mess.TTSwapError.71"); }
        case "72": { return t("common.mess.TTSwapError.72"); }
        case "73": { return t("common.mess.TTSwapError.73"); }
        case "74": { return t("common.mess.TTSwapError.74"); }
        case "75": { return t("common.mess.TTSwapError.75"); }
        case "76": { return t("common.mess.TTSwapError.76"); }
        case "77": { return t("common.mess.TTSwapError.77"); }
        case "78": { return t("common.mess.TTSwapError.78"); }
        case "79": { return t("common.mess.TTSwapError.79"); }
        case "80": { return t("common.mess.TTSwapError.80"); }
        case "81": { return t("common.mess.TTSwapError.81"); }
        case "82": { return t("common.mess.TTSwapError.82"); }
        case "83": { return t("common.mess.TTSwapError.83"); }
        case "84": { return t("common.mess.TTSwapError.84"); }
        case "85": { return t("common.mess.TTSwapError.85"); }
        case "86": { return t("common.mess.TTSwapError.86"); }
        case "87": { return t("common.mess.TTSwapError.87"); }
        case "88": { return t("common.mess.TTSwapError.88"); }
        case "89": { return t("common.mess.TTSwapError.89"); }
        case "90": { return t("common.mess.TTSwapError.90"); }
        case "91": { return t("common.mess.TTSwapError.91"); }
        case "92": { return t("common.mess.TTSwapError.92"); }
        case "93": { return t("common.mess.TTSwapError.93"); }
        case "94": { return t("common.mess.TTSwapError.94"); }
        case "95": { return t("common.mess.TTSwapError.95"); }
        case "96": { return t("common.mess.TTSwapError.96"); }
        case "97": { return t("common.mess.TTSwapError.97"); }
        case "98": { return t("common.mess.TTSwapError.98"); }
        case "99": { return t("common.mess.TTSwapError.99"); }
        case "100": { return t("common.mess.TTSwapError.100"); }
        case "6c0f429e": { return t("common.mess.error.NativeETHTransferFailed()"); }
        case "f27f64e4": { return t("common.mess.error.ERC20TransferFailed()"); }
        case "40754b6a": { return t("common.mess.error.ERC20PermitFailed()"); }
        case "8baa579f": { return t("common.mess.error.InvalidSignature()"); }
        case "4be6321b": { return t("common.mess.error.InvalidSignatureLength()"); }
        case "815e1d64": { return t("common.mess.error.InvalidSigner()"); }
        case "d81b2f2e": { return t("common.mess.error.AllowanceExpired(uint256)"); }
        case "24d35a26": { return t("common.mess.error.ExcessiveInvalidation()"); }
        case "f96fb071": { return t("common.mess.error.InsufficientAllowance(uint256)"); }
        case "3728b83d": { return t("common.mess.error.InvalidAmount(uint256)"); }
        case "b0669cbc": { return t("common.mess.error.InvalidContractSignature()"); }
        case "756688fe": { return t("common.mess.error.InvalidNonce()"); }
        case "ff633a38": { return t("common.mess.error.LengthMismatch()"); }
        case "cd21db4f": { return t("common.mess.error.SignatureExpired(uint256)"); }
    }
}